Element 123456 in a set in the family, but not in the main set!
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
